PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS UserConnection;
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS Friend;
DROP TABLE IF EXISTS UserRoom;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Room;

CREATE TABLE User (
	userID INTEGER PRIMARY KEY AUTOINCREMENT,
	username VARCHAR(20) UNIQUE NOT NULL,
	password VARCHAR(20) NOT NULL
);

CREATE TABLE UserConnection (
	userID INTEGER,
	ip VARCHAR(15),
	port INTEGER,
	FOREIGN KEY(userID) REFERENCES User(userID)
		ON UPDATE CASCADE
);

CREATE TABLE Message (
	messageID INTEGER PRIMARY KEY AUTOINCREMENT,
	userID INTEGER,
	roomID INTEGER,
	message VARCHAR(1000),
	sentDate DATETIME,
	FOREIGN KEY(userID) REFERENCES User(userID)
				ON UPDATE CASCADE,
	FOREIGN KEY(roomID) REFERENCES Room(roomID)
				ON UPDATE CASCADE
);

CREATE TABLE Room (
	roomID INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(50)
);

CREATE TABLE Friend (
	firstUserID INTEGER,
	secondUserID INTEGER,
	FOREIGN KEY(firstUserID) REFERENCES User(userID)
				ON UPDATE CASCADE,
	FOREIGN KEY(secondUserID) REFERENCES User(userID)
				ON UPDATE CASCADE,
	PRIMARY KEY(firstUserID, secondUserID)
);

CREATE TABLE UserRoom (
	userID INTEGER,
	roomID INTEGER,
	FOREIGN KEY(userID) REFERENCES User(userID)
				ON UPDATE CASCADE,
	FOREIGN KEY(roomID) REFERENCES Room(roomID)
				ON UPDATE CASCADE,
	PRIMARY KEY(userID, roomID)
);

INSERT INTO User(username, password) VALUES ('vascoUP', 'vascoUP');
INSERT INTO User(username, password) VALUES('saraUP', 'saraUP');
INSERT INTO Room(name) VALUES('sala1');
INSERT INTO UserRoom(userID, roomID) VALUES (1,1);
INSERT INTO Friend(firstUserID, secondUserID) VALUES(1,2);